apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: logging-poc-ingress
  namespace: {{ namespace }}
spec:
  tls:
    - secretName: logging-poc-tls
      hosts:
        - {{ hostname }}
  rules:
    - host: {{ hostname }}
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: logging-poc-service
                port:
                  name: javalin-port