services:
#  api:
#    image: ghcr.io/ruchira088/logging-poc-api:dev
#    ports:
#      - "8080:8080"
#    depends_on:
#      - logstash
#    volumes:
#      - ./log-config:/opt/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.1.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health"]
      start_period: 15s
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"

  logstash:
    image: docker.elastic.co/logstash/logstash:9.1.0
    volumes:
      - ./elk/logstash/pipeline.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    ports:
      - "5001:5001"
      - "5002:5002"
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:9.1.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - XPACK_SECURITY_ENABLED=false
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch