x-passwords:
  ELASTICSEARCH_PASSWORD: &elasticsearch-password "my-password"
  KIBANA_USERNAME: &kibana-username "kibana-username"
  KIBANA_PASSWORD: &kibana-password "kibana-password"
  LOGSTASH_USERNAME: &logstash-username "logstash-username"
  LOGSTASH_PASSWORD: &logstash-password "logstash-password"

services:
  api:
    image: ghcr.io/ruchira088/logging-poc-api:main
    ports:
      - "8080:8080"
    depends_on:
      logstash:
        condition: service_healthy
    volumes:
      - ./log-config:/opt/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.1.0
    healthcheck:
      test: "curl -f -u elastic:$${ELASTIC_PASSWORD} http://localhost:9200/_cluster/health"
      start_period: 5s
      interval: 10s
      timeout: 5s
      retries: 10
    mem_limit: 4g
    environment:
      ELASTIC_PASSWORD: *elasticsearch-password
      "discovery.type": single-node
      "xpack.security.http.ssl.enabled": false

  logstash:
    image: docker.elastic.co/logstash/logstash:9.1.0
    volumes:
      - ./elk/logstash/pipeline.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    ports:
      - "5001:5001"
      - "5002:5002"
    healthcheck:
      test: "curl -f http://localhost:9600/"
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      elasticsearch:
        condition: service_healthy
      elasticsearch-users:
        condition: service_completed_successfully
    environment:
      ELASTICSEARCH_HOST: "http://elasticsearch:9200"
      ELASTICSEARCH_USERNAME: *logstash-username
      ELASTICSEARCH_PASSWORD: *logstash-password

  elasticsearch-users:
    image: curlimages/curl
    depends_on:
      elasticsearch:
        condition: service_healthy
    command:
      - /opt/scripts/create_users.sh
    volumes:
      - ./elk/elasticsearch:/opt/scripts
    environment:
      ELASTICSEARCH_HOST: "http://elasticsearch:9200"
      ELASTICSEARCH_USERNAME: "elastic"
      ELASTICSEARCH_PASSWORD: *elasticsearch-password
      KIBANA_USERNAME: *kibana-username
      KIBANA_PASSWORD: *kibana-password
      LOGSTASH_USERNAME: *logstash-username
      LOGSTASH_PASSWORD: *logstash-password

  kibana:
    image: docker.elastic.co/kibana/kibana:9.1.0
    depends_on:
      elasticsearch:
        condition: service_healthy
      elasticsearch-users:
        condition: service_completed_successfully
    healthcheck:
      test: "curl -f http://localhost:5601/status"
      start_period: 5s
      interval: 10s
      timeout: 5s
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
      ELASTICSEARCH_USERNAME: *kibana-username
      ELASTICSEARCH_PASSWORD: *kibana-password
