FROM eclipse-temurin:21-jre

LABEL org.opencontainers.image.source=https://github.com/ruchira088/logging-poc

ENV GIT_BRANCH {{ git_branch }}
ENV GIT_COMMIT {{ git_commit }}
ENV BUILD_TIMESTAMP {{ build_timestamp }}

WORKDIR /opt/logging-poc-{{ app }}

ADD {{ app }}.tar .

CMD [ "/opt/logging-poc-{{ app }}/{{ app }}/bin/{{ app }}" ]
